-- Copyright (c) 2021, 2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (1, 'ORG-ALP', 'Alpenglow Distribution', 1001);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (2, 'ORG-MST', 'Mistwood Supply Hub', 1002);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (3, 'ORG-CRN', 'Crimsonridge Storage', 1003);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (4, 'ORG-VLY', 'Valedale Fulfillment Center', 1004);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (5, 'ORG-ELM', 'Elmbrook Logistics', 1005);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (6, 'ORG-SVN', 'Savannah Nexus Facility', 1006);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (7, 'ORG-GLB', 'Glistening Bay Storage', 1007);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (8, 'ORG-RVR', 'Riverbend Depot', 1008);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (9, 'ORG-PIN', 'Pinecrest Warehouse', 1009);
INSERT INTO INV_ORG (INV_ORG_ID, ORG_CODE, ORG_NAME, LOCATION_ID) VALUES (10, 'ORG-FSR', 'Frostspire Center', 1010);