-- Copyright (c) 2021, 2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (100, 'ITM-001', 'Widget A', 'FG');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (101, 'ITM-002', 'Widget B', 'FG');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (102, 'ITM-003', 'Sprocket', 'RM');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (103, 'ITM-004', 'Gear Set', 'FG');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (104, 'ITM-005', 'Bearing', 'RM');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (105, 'ITM-006', 'Assembly Kit', 'FG');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (106, 'ITM-007', 'Pump', 'FG');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (107, 'ITM-008', 'Sealant', 'RM');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (108, 'ITM-009', 'Belt', 'RM');
INSERT INTO INV_ITEMS (ITEM_ID, ITEM_NUMBER, ITEM_DESCRIPTION, ITEM_TYPE) VALUES (109, 'ITM-010', 'Coupling', 'FG');