-- Copyright (c) 2021, 2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (1, 1, 100, 150, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (2, 1, 101, 100, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (3, 2, 102, 225, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (4, 2, 103, 200, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (5, 3, 104, 180, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (6, 3, 105, 155, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (7, 4, 106, 120, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (8, 5, 107, 210, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (9, 6, 108, 75, TO_DATE('01-JAN-2024','DD-MON-YYYY'));
INSERT INTO INV_ONHAND_QTY (ONHAND_ID, INV_ORG_ID, ITEM_ID, QTY_ON_HAND, AS_OF_DATE) VALUES (10, 7, 109, 50, TO_DATE('01-JAN-2024','DD-MON-YYYY'));