-- Copyright (c) 2021, 2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (11, 1, NULL, 'LINE', 1000.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (12, 2, NULL, 'CHARGES', 500.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (13, 3, NULL, 'TAX', 75.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (14, 4, NULL, 'FREIGHT', 80.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (15, 5, NULL, 'LINE', 1200.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (16, 6, NULL, 'CHARGES', 300.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (17, 7, NULL, 'TAX', 95.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (18, 8, NULL, 'LINE', 1800.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (19, 9, NULL, 'LINE', 1350.00);
INSERT INTO RA_CUSTOMER_TRX_LINES (CUSTOMER_TRX_LINE_ID, CUSTOMER_TRX_ID, LINK_TO_CUST_TRX_LINE_ID, LINE_TYPE, EXTENDED_AMOUNT) VALUES (20, 10, NULL, 'TAX', 110.00);