-- Copyright (c) 2021, 2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (1, 'INV-1001', 101, TO_DATE('01-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (2, 'INV-1002', 102, TO_DATE('02-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (3, 'INV-1003', 103, TO_DATE('03-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (4, 'DM-1004', 104, TO_DATE('04-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (5, 'CM-1005', 105, TO_DATE('05-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (6, 'INV-1006', 106, TO_DATE('06-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (7, 'INV-1007', 107, TO_DATE('07-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (8, 'INV-1008', 108, TO_DATE('08-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (9, 'DM-1009', 109, TO_DATE('09-JAN-24','DD-MON-RR'));
INSERT INTO RA_CUSTOMER_TRX (CUSTOMER_TRX_ID, TRX_NUMBER, BILL_TO_CUSTOMER_ID, TRX_DATE) VALUES (10, 'CM-1010', 110, TO_DATE('10-JAN-24','DD-MON-RR'));