-- Copyright (c) 2021, 2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (201, 500.00, 'UNAPP', 'RCPT-0001', 'CASH');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (202, 900.00, 'APP', 'RCPT-0002', 'CASH');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (203, 400.00, 'UNID', 'RCPT-0003', 'MISC');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (204, 1200.00, 'APP', 'RCPT-0004', 'CASH');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (205, 300.00, 'UNAPP', 'RCPT-0005', 'MISC');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (206, 800.00, 'REV', 'RCPT-0006', 'CASH');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (207, 725.00, 'APP', 'RCPT-0007', 'CASH');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (208, 450.00, 'UNID', 'RCPT-0008', 'MISC');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (209, 1050.00, 'APP', 'RCPT-0009', 'CASH');
INSERT INTO AR_CASH_RECEIPTS (CASH_RECEIPT_ID, AMOUNT, STATUS, RECEIPT_NUMBER, TYPE) VALUES (210, 640.00, 'NSF', 'RCPT-0010', 'CASH');